### ISSUE TITLE
What is REGISTER_COMMANDS_KEY?

### ISSUE THREAD

**Issue by MooKorea** [mmvergara/nextjs-discord-bot-boilerplate#1]
In the example .env file, the REGISTER_COMMANDS_KEY value doesn't show up anywhere in the discord developer portal.

I'm also assuming BOT_TOKEN is the "Client Secret", and NEXT_PUBLIC_CLIENT_APPLICATION_ID is supposed to be the Application ID found in the "General Information" tab. Otherwise, these environment variable names seem to be outdated.

**Comment by mmvergara** [comment]
@MooKorea 

- Register Commands Key is something you set on your own. then use it to register your commands on the deployment website. ( i apologive for the bad documentation, added more info)
- BOT_TOKEN is this
![image](https://github.com/mmvergara/nextjs-discord-bot-boilerplate/assets/104471209/09914dec-1e70-4cf6-9fe0-1fbec86e1ec6)
- `NEXT_PUBLIC_CLIENT_APPLICATION_ID` is now renamed to `NEXT_PUBLIC_APPLICATION_ID` Thanks <3.
